spring:
  banner:
    image:
      location: images\wechat.png
application:
  name: DEV
env:
  name: ENV-DEV
  max-length: 100
  require: false
  security:
    username: admin
    password: password
    roles:
      - USER
      - ADMIN
      - SUPER_ADMIN
my:
  servers:
    - dev.bonjourcs.com
    - tools.bonjourcs.com
    - open.bonjourcs.com
  duration:
    current-live: 10
    time-to-live: 1000
system:
  period:
    current-time: 22
    time-to-live: 100

properties:
  weight:
    max-weight: "1500"
server:
  servlet:
    session:
      cookie:
        name: WEB-SESSION-0
