spring:
  banner:
    image:
      location: images\wechat.png
application:
  name: DEV
env:
  name: ENV-DEV
  max-length: 100
  require: false
  security:
    username: admin
    password: password
    roles:
      - USER
      - ADMIN
      - SUPER_ADMIN
my:
  servers:
    - dev.bonjourcs.com
    - tools.bonjourcs.com
    - open.bonjourcs.com
