spring:
  security:
    user:
      password: weak
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration
logging:
  level:
    web: ERROR
server:
  port: 18000
